language: node_js
node_js: stable
branches:
  only:
  - /^release\/.*$/
before_install:
- export TZ='Asia/Shanghai'
install:
- npm install
script:
- hexo clean
- hexo generate
after_success:
# - cd .public
# - git init
- git config --global user.name "d0ngy1n"
- git config --global user.email "d0ngy1n@163.com"
# - git add .
# - git commit -m 'x'
# - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
- sed -i'' "s~git@github.com:${GH_REF}~https://${GH_TOKEN}:x-oauth-basic@github.com/${GH_REF}~" _config.yml
#- sed -i'' "s~#{leancloud_username}~${LC_USERNAME}~" _config.yml
#- sed -i'' "s~#{leancloud_password}~${LC_PASSWORD}~" _config.yml
- hexo deploy
env:
  global:
  - GH_REF: d0ngy1n/d0ngy1n.github.io.git
