# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/d0ngy1n
  # Twitter: https://twitter.com/
  分类: /categories
  归档: /archives
  标签云: /tags


# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: true

# 默认音乐
mp3: 
  - https://datashat.net/music_for_programming_25-_nono_.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '486e44393db994596d10'
    # 应用秘钥
    clientSecret: '8800cfb59da1202122ea9b1ace74aba4bf371085'
    # issue仓库名
    repo: 'd0ngy1n.github.io'
    # Github名
    owner: 'd0ngy1n'
    # Github名  
    admin: ['d0ngy1n']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: DongYin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-139580542-1

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
